model {
  file: "model.sdf"
}
name: "Xyli_Pure_Xylitol"
description: "Xyli Pure Xylitol"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Jarrow Formulas"
}
annotations {
  key: "gtin"
  value: "790011800026"
}
annotations {
  key: "mpn"
  value: "790011800026"
}
annotations {
  key: "sku"
  value: "XYLI16"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Bottles and Cans and Cups"
}
