model {
  file: "model.sdf"
}
name: "Wrigley_Orbit_Mint_Variety_18_Count"
description: "Wrigley Orbit Mint Variety 18 Count"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Wrigley"
}
annotations {
  key: "gtin"
  value: "00022000114372"
}
annotations {
  key: "sku"
  value: "00022000114372"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
