model {
  file: "model.sdf"
}
name: "MY_MOOD_MEMO"
description: "MY MOOD MEMO\nThe set consists of 24 wooden tiles with 12 different emotions. Children can learn how to match two identical emotions with this fun memory game! Skills include learning about the relationship of colors and emotions. Emotion Color Wheel can help visually group feeling and practice emotion vocabulary."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "5656"
}
annotations {
  key: "sku"
  value: "05656P00"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
