model {
  file: "model.sdf"
}
name: "INTERNATIONAL_PAPER_Willamette_4_Brown_Bag_500Count"
description: "INTERNATIONAL PAPER Willamette #4 Brown Bag 500-Count"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "INTERNATIONAL"
}
annotations {
  key: "gtin"
  value: "00032476500043"
}
annotations {
  key: "sku"
  value: "00032476500043"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
