model {
  file: "model.sdf"
}
name: "Tetris_Link_Game"
description: "Tetris Link Game"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Techno Source"
}
annotations {
  key: "gtin"
  value: "00801561016000"
}
annotations {
  key: "sku"
  value: "801561016000"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Board Games"
}
