model {
  file: "model.sdf"
}
name: "LEGO_5887_Dino_Defense_HQ"
description: "LEGO 5887 Dino Defense HQ"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Lego"
}
annotations {
  key: "gtin"
  value: "00673419167116"
}
annotations {
  key: "sku"
  value: "673419167116"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Legos"
}
