model {
  file: "model.sdf"
}
name: "Hefty_Waste_Basket_Decorative_Bronze_85_liter"
description: "Hefty Waste Basket, Decorative, Bronze - 8.5 liter"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Hefty"
}
annotations {
  key: "gtin"
  value: "00025947067213"
}
annotations {
  key: "sku"
  value: "00025947067213"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
