model {
  file: "model.sdf"
}
name: "SPEED_BOAT"
description: "SPEED BOAT\nImagine racing across the sea at super speeds! This delightful set stimulates interactive and imaginative play."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "5667"
}
annotations {
  key: "sku"
  value: "05667P00"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
