model {
  file: "model.sdf"
}
name: "Kanex_MultiSync_Wireless_Keyboard"
description: "Kanex Multi-Sync - Wireless Keyboard"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Kanex"
}
annotations {
  key: "gtin"
  value: "00814556015292"
}
annotations {
  key: "sku"
  value: "00814556015292"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Keyboard"
}
