model {
  file: "model.sdf"
}
name: "Clorox_Premium_Choice_Gloves_SM_1_pair"
description: "Clorox Premium Choice Gloves, S/M - 1 pair\n1 pair foam lined latex 13\" cuff gloves. Moisturized with glycerine."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Clorox"
}
annotations {
  key: "gtin"
  value: "00765060992077"
}
annotations {
  key: "sku"
  value: "00765060992077"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
