model {
  file: "model.sdf"
}
name: "Asus_Z97AR_LGA_1150_Intel_ATX_Motherboard"
description: "Asus Z97-AR LGA 1150 Intel ATX Motherboard"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Asus"
}
annotations {
  key: "gtin"
  value: "00886227773633"
}
annotations {
  key: "sku"
  value: "886227773633"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
