model {
  file: "model.sdf"
}
name: "Razer_Taipan_Black_Ambidextrous_Gaming_Mouse"
description: "Razer Taipan Black - Ambidextrous Gaming Mouse\nThe Razer Taipan offers 9 Hyperesponse buttons and is ergonomically designed for both right and left handed users. The 8200dpi 4G laser sensor also offers exceptional tracking precision with zero interpolation for high-performance wired gameplay."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Razer"
}
annotations {
  key: "gtin"
  value: "879862004736"
}
annotations {
  key: "mpn"
  value: "rz01-00780100-r3u1"
}
annotations {
  key: "sku"
  value: "879862004736"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Mouse"
}
