model {
  file: "model.sdf"
}
name: "JA_Henckels_International_Premio_Cutlery_Block_Set_14Piece"
description: "J.A. Henckels International Premio Cutlery Block Set, 14-Piece"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "J.A."
}
annotations {
  key: "gtin"
  value: "00035886257590"
}
annotations {
  key: "sku"
  value: "00035886257590"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
