model {
  file: "model.sdf"
}
name: "Room_Essentials_Dish_Drainer_Collapsible_White"
description: "Room Essentials Dish Drainer, Collapsible, White"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Room Essentials"
}
annotations {
  key: "gtin"
  value: "00764195888002"
}
annotations {
  key: "sku"
  value: "00764195888002"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
