model {
  file: "model.sdf"
}
name: "Black_Decker_Stainless_Steel_Toaster_4_Slice"
description: "Black & Decker Stainless Steel Toaster, 4 Slice"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Black"
}
annotations {
  key: "gtin"
  value: "00050875809437"
}
annotations {
  key: "sku"
  value: "00050875809437"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
