model {
  file: "model.sdf"
}
name: "Canon_Pixma_Ink_Cartridge_8_Red"
description: "Canon Pixma Ink Cartridge, 8 Red"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Canon"
}
annotations {
  key: "gtin"
  value: "00013803051186"
}
annotations {
  key: "sku"
  value: "00013803051186"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
