model {
  file: "model.sdf"
}
name: "LEGO_Duplo_Build_and_Play_Box_4629"
description: "LEGO Duplo Build and Play Box (4629)"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "LEGO"
}
annotations {
  key: "gtin"
  value: "00673419168205"
}
annotations {
  key: "sku"
  value: "00673419168205"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Legos"
}
