model {
  file: "model.sdf"
}
name: "Digital_Camo_Double_Decker_Lunch_Bag"
description: "Digital Camo Double Decker Lunch Bag"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Wildkin"
}
annotations {
  key: "gtin"
  value: "097277524032"
}
annotations {
  key: "mpn"
  value: "52403"
}
annotations {
  key: "sku"
  value: "52403"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Bag"
}
