model {
  file: "model.sdf"
}
name: "Black_and_Decker_TR3500SD_2Slice_Toaster"
description: "Black and Decker TR3500SD 2-Slice Toaster"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Black"
}
annotations {
  key: "gtin"
  value: "00050875812529"
}
annotations {
  key: "sku"
  value: "00050875812529"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
