model {
  file: "model.sdf"
}
name: "TriStar_Products_PPC_Power_Pressure_Cooker_XL_in_Black"
description: "Tri-Star Products PPC Power Pressure Cooker XL in Black"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Tri-Star"
}
annotations {
  key: "gtin"
  value: "00752356798864"
}
annotations {
  key: "sku"
  value: "00752356798864"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
