model {
  file: "model.sdf"
}
name: "Marc_Anthony_True_Professional_Oil_of_Morocco_Argan_Oil_Treatment"
description: "Marc Anthony True Professional Oil of Morocco Argan Oil Treatment"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Marc"
}
annotations {
  key: "gtin"
  value: "00621732300031"
}
annotations {
  key: "sku"
  value: "00621732300031"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
