model {
  file: "model.sdf"
}
name: "Timberland_Mens_Earthkeepers_Newmarket_6Inch_Cupsole_Boot"
description: "Timberland Men\'s Earthkeepers Newmarket 6-Inch Cupsole Boot\nRugged, durable and hard-wearing Men\'s Earthkeepers Newmarket 6-Inch Cupsole Boot. We\'ve been using nubuck leather to craft our hard-wearing boots for decades - and our Earthkeepers Newmarket 6-Inch Cupsole is the latest version of a classic style. Men\'s Earthkeepers Newmarket 6-Inch Cupsole Boot. We\'ve been using nubuck leather to craft our hard-wearing boots for decades - and our Earthkeepers Newmarket 6-Inch Cupsole is the latest version of a classic style."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Timberland Pro"
}
annotations {
  key: "gtin"
  value: "887235297821"
}
annotations {
  key: "mpn"
  value: "6669r"
}
annotations {
  key: "sku"
  value: "13665222"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Shoe"
}
