model {
  file: "model.sdf"
}
name: "Office_Depot_HP_71_Remanufactured_Ink_Cartridge_Black"
description: "Office Depot (HP 71) Remanufactured Ink Cartridge - Black"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Office"
}
annotations {
  key: "gtin"
  value: "00841992060302"
}
annotations {
  key: "sku"
  value: "00841992060302"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
