model {
  file: "model.sdf"
}
name: "Now_Designs_Bowl_Akita_Black"
description: "Now Designs Bowl, Akita, Black"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Now Designs"
}
annotations {
  key: "gtin"
  value: "00064180220719"
}
annotations {
  key: "sku"
  value: "00064180220719"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
